/*
 * This source file was generated by the Gradle 'init' task
 */
package proyecto.simulador.bancario;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class MainAppTest {
    @Test void appHasAGreeting() {
        MainApp classUnderTest = new MainApp();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
