plugins {
    id 'application'
    // 1. Agregamos el plugin de JavaFX
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation libs.junit.jupiter
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    // Mantengo Guava por si lo usas, pero no es necesario para JavaFX
    implementation libs.guava
}

// 2. Configuración específica de JavaFX
javafx {
    version = "21"
    modules = [ 'javafx.controls', 'javafx.fxml' ]
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = 'proyecto.simulador.bancario.MainApp'
}

tasks.named('test') {
    useJUnitPlatform()
}